ShopApp/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('category/<slug:cat_slug>/', Categories.as_view(), name='category'),
    path('products/<slug:product_slug>/', ShowProduct.as_view(), name='product'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('cancel-payment/', CancelView, name=' cancel'),
    path('success-payment/', SuccessView, name='success'),
]

ShopSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ShopSite import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('checkout/', include('payments.urls', namespace='payments')),
                  path('', include('ShopApp.urls', namespace='shop')),
                  path('favourites/', include('favourites.urls', namespace='favourites')),
                  path('feedback/', include('feedback.urls', namespace='feedback')),
                  path('account/', include('account.urls', namespace='account'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

favourites/urls.py
from .views import *
from django.urls import path

app_name = 'favourites'

urlpatterns = [
        path('', favourites_list, name='favourites_list'),
        path('add/<int:product_id>/', add_to_favourites, name='add_to_favourites'),
        path('remove/<int:product_id>/', remove_from_favourites, name='remove_from_favourites'),
]

favourites/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ShopApp.models import Product
from ShopApp.utils import menu
from cart.forms import CartAddProductForm
from .favourites import Favourites

"""
add_to_favourites - Добавление товара в список избранного.
favourites_list - Отображения списка избранного, empty - нужен для проверки на то, пустой список или нет,
так же добавляем CartAddProductForm для перенаправления на покупку товара.
remove_from_favourites - Удаление товара из списка избранного.
"""


@require_POST
def add_to_favourites(request, product_id):
    favourites = Favourites(request)
    product = get_object_or_404(Product, id=product_id)
    favourites.add(product=product)
    return redirect('favourites:favourites_list')


def favourites_list(request):
    favourites = Favourites(request)
    empty = True

    for item in favourites:
        if (item['price'] == 0) and (item['name'] == 0):
            empty = True
        else:
            empty = False

    context = {
        'favourites': favourites,
        'menu': menu,
        'empty': empty,
        'title': 'Избранное',
        'cart_product_form': CartAddProductForm,
    }
    return render(request, 'favourites/list.html', context=context)


def remove_from_favourites(request, product_id):
    cart = Favourites(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('favourites:favourites_list')

favourites/templates/favourites/list.html
{% extends "ShopApp/base.html" %}
{% load static %}
{% block categories %}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="col-md-12">
        {% if empty %}
        <div class="d-flex justify-content-center" style="margin-top:10%;margin-bottom:10%;">
            <ul>
                <li>
                    <h1>Вы ничего не добавили в Избранное</h1>
                </li>
                <li class="text-center">
                    <a href="{% url 'shop:home' %}" class="text-scope">Вернуться к покупкам</a>
                </li>
            </ul>
        </div>
        {% else %}
        {% for item in favourites %}
        {% with product=item.product %}
        <div class="card mb-8" style="max-width:1100px; max-height:200px;">
            <div class="row no-gutters">
                <div class="col-md-4 d-flex justify-content-center align-items-center">
                    <img src="{{ product.image.url }}" class="card-img" style="width:100px;height:100px;">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5><a href="{{ product.get_absolute_url }}" class="card-title text-scope">{{ product.name }}</a>
                        </h5>
                        <p class="card-text">{{ product.price }}&#8381;</p>
                        <ul class="nav col-md-6 mb-2 mb-md-0 d-flex justify-content-start">
                            <li class="d-flex align-items-end">
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    <p style="display: none; height:0px; width:0px;">{{ cart_product_form }}</p>
                                    {% csrf_token %}
                                    <button type="submit"
                                            style="border: none; outline: none; background: transparent; padding: 0 0;">
                                        <p class="text-scope">Добавить в корзину</p><img
                                            src="{% static 'ShopApp/image/cart.svg'%}"
                                            style="margin-left:10px; width:20px;"></button>
                                </form>
                            </li>
                            <li class="d-flex align-items-end">
                                <form action="{% url 'favourites:remove_from_favourites' product.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit"
                                            style="border: none; outline: none; background: transparent; padding: 0 0;">
                                        <p class="text-scope">Убрать из избранного</p>
                                    </button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}