ShopApp/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('category/<slug:cat_slug>/', Categories.as_view(), name='category'),
    path('products/<slug:product_slug>/', ShowProduct.as_view(), name='product'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('cancel-payment/', CancelView, name=' cancel'),
    path('success-payment/', SuccessView, name='success'),
]

ShopSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ShopSite import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('checkout/', include('payments.urls', namespace='payments')),
                  path('', include('ShopApp.urls', namespace='shop')),
                  path('favourites/', include('favourites.urls', namespace='favourites')),
                  path('feedback/', include('feedback.urls', namespace='feedback')),
                  path('account/', include('account.urls', namespace='account'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

payments/urls.py
from django.urls import path
from .views import CreateCheckoutSessionView

app_name = 'payments'

urlpatterns = [
    path('create-checkout-session/<pk>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

"""
Форма добавление товара в корзину
"""


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
    )
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput,
                                )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ShopApp.models import Product
from ShopApp.utils import menu
from .cart import Cart
from .forms import CartAddProductForm

"""
cart_add - добавление товара, которое мы получили из формы и дальнейшее перенаправление в корзину.
cart_remove - удаление товара из корзины и дальнейшее перенаправление в корзину.
cart_detail - отображение корзины.
"""


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'],
                 )

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True}, )

    return render(request, 'cart/detail.html',
                  {'cart': cart, 'menu': menu, 'title': 'Корзина'})

cart/templates/cart/detail.html
{% extends "ShopApp/base.html" %}
{% load static %}
{% block categories %}
{% endblock %}
{% block content %}
{% if cart.get_total_price == 0 %}
        <div class="d-flex justify-content-center" style="margin-top:15%;margin-bottom:15%;">
            <ul>
                <li>
                    <h1>Корзина пустая</h1>
                </li>
                <li class="text-center">
                    <a href="{% url 'shop:home' %}" class="text-scope">Вернуться к покупкам</a>
                </li>
            </ul>
        </div>
{% else %}
<ul class="list-group">
    <li class="list-group-item"><h1>Корзина покупок</h1></li>
    <li class="list-group-item"><p>Сумма к оплате: {{ cart.get_total_price }}&#8381;</p></li>
</ul>

<div class="table-responsive">
    <table class="table">
        <thead class="table-dark">
        <tr>
            <th>Картинка</th>
            <th>Товар</th>
            <th></th>
            <th>Количество</th>
            <th>Цена за шт</th>
            <th>Общая стоимость</th>
            <th>Оплата</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td><a href="{{ u.get_absolute_url }}" class="text-scope">{{ product.name }}</a></td>
            <td>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update.as_hidden }}
                    <input type="submit" value="Добавить" class="btn btn-outline-secondary btn-sm">
                </form>
            </td>
            <td>
                <button type="button" class="btn btn-outline-secondary btn-sm"><a
                        href="{% url 'cart:cart_remove' product.id %}" style="text-decoration: none; color: inherit;">Удалить</a>
                </button>
            </td>

            <td>
                {{ item.quantity }}

            </td>
            <td class="num">{{ item.price }}&#8381;</td>
            <td class="num">{{ item.total_price }}&#8381;</td>
            <td>
                <form action="{% url 'payments:create-checkout-session' product.id %}" method="post">
                    {% csrf_token %}
                    <p style="display: none; height:0px; width:0px;">{{ item.update_quantity_form.quantity }}</p>
                    <input type="submit" value="Оплата" class="btn btn-outline-secondary btn-sm">
                </form>
            </td>
        </tr>
        {% endwith %}
        {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% endblock %}