ShopApp/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('category/<slug:cat_slug>/', Categories.as_view(), name='category'),
    path('products/<slug:product_slug>/', ShowProduct.as_view(), name='product'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('cancel-payment/', CancelView, name=' cancel'),
    path('success-payment/', SuccessView, name='success'),
]

ShopSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ShopSite import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('checkout/', include('payments.urls', namespace='payments')),
                  path('', include('ShopApp.urls', namespace='shop')),
                  path('favourites/', include('favourites.urls', namespace='favourites')),
                  path('feedback/', include('feedback.urls', namespace='feedback')),
                  path('account/', include('account.urls', namespace='account'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('', account_detail, name='account_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

favourites/urls.py
from .views import *
from django.urls import path

app_name = 'favourites'

urlpatterns = [
        path('', favourites_list, name='favourites_list'),
        path('add/<int:product_id>/', add_to_favourites, name='add_to_favourites'),
        path('remove/<int:product_id>/', remove_from_favourites, name='remove_from_favourites'),
]

ShopApp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

"""
Имеется две модели - Category и Product.
В модели Product мы задаем цену, название, изображение и т.д.
Category нужна для того, чтобы связать определенный продукт с определенной категорией
"""


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='URL')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('shop:category', kwargs={'cat_slug': self.slug})

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Наименование товара')
    slug = models.SlugField(max_length=200, db_index=True, unique=True, verbose_name='URL')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Изображение товара')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Стоимость (в рублях)')
    stock = models.PositiveIntegerField(verbose_name='Количество товара')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Время создание позиции')
    updated = models.DateTimeField(auto_now=True, verbose_name='Последнее время изменения позиции')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Позиции товаров'
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('shop:product', kwargs={'product_slug': self.slug})

    def __str__(self):
        return self.name

    def get_display_price(self):
        return "{0:.2f}".format(self.price / 100)

ShopApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

"""
Модель пользователя взята, для его регистрации, путем передачи значений в формы RegisterUserForm и LoginUserForm
Настроены нужные поля для регистрации и авторизации.
"""


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', required=True, widget=forms.TextInput(attrs={'class': 'form-label'}))
    email = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class': 'form-label'}))
    first_name = forms.CharField(label='Имя', required=True, widget=forms.TextInput(attrs={'class': 'form-label'}))
    last_name = forms.CharField(label='Фамилия', required=True, widget=forms.TextInput(attrs={'class': 'form-label'}))
    password1 = forms.CharField(label='Пароль', required=True, widget=forms.TextInput(attrs={'class': 'form-label'}))
    password2 = forms.CharField(label='Повтор пароля', required=True, widget=forms.TextInput(attrs={'class': 'form-label'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', required=True, widget=forms.TextInput(attrs={'class': 'form-label'}))
    password = forms.CharField(label='Пароль', required=True, widget=forms.TextInput(attrs={'class': 'form-label'}))

ShopApp/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from .forms import *
from .utils import *


class Home(Mixin, ListView):
    model = Product
    template_name = 'ShopApp/index.html'
    context_object_name = 'unit'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_user_context(title='Магазин'))
        return context

    def get_queryset(self):
        # Оптимизация запросов
        return Product.objects.filter(available=True).select_related('category')


class Categories(Mixin, ListView):
    model = Product
    template_name = 'ShopApp/index.html'
    context_object_name = 'unit'
    allow_empty = False

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['cat_slug'], available=True).select_related('category')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c = Category.objects.get(slug=self.kwargs['cat_slug'])
        c_def = self.get_user_context(title=str(c.name), cat_selected=c.pk)
        return dict(list(context.items()) + list(c_def.items()))


class ShowProduct(Mixin, DetailView):
    model = Product
    template_name = 'ShopApp/show_product.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_user_context(title=context['product']))
        return context


class RegisterUser(Mixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'ShopApp/register.html'
    success_url = reverse_lazy('shop:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_user_context(title='Регистрация'))
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shop:home')


class LoginUser(Mixin, LoginView):
    form_class = LoginUserForm
    template_name = 'ShopApp/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_user_context(title='Авторизация'))
        return context

    def get_success_url(self):
        return reverse_lazy('shop:home')


def logout_user(request):
    logout(request)
    return redirect('shop:home')


def SuccessView(request):
    context = {
        'title': 'Успех',
    }
    return render(request, 'payments/success.html', context=context)


def CancelView(request):
    context = {
        'title': 'Отмена',
    }
    return render(request, 'payments/cancel.html', context=context)

ShopApp/templates/ShopApp/about.html
{% extends 'ShopApp/base.html' %}
{% load static %}
{% block categories %}
{% endblock %}
{% block content %}
<div class="text-center col-md-12">
    <h1 style="margin-top:10%;">О сайте</h1>
    <ul class="nav d-flex justify-content-center py-5" style="margin-bottom:20%;">
        <li>Телеграм</li>
        <li>Гитхаб</li>
        <li>hh</li>
    </ul>
</div>
{% endblock %}

ShopApp/templates/ShopApp/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <link href="{% static 'ShopApp/css/style.css'%}" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css"
          integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>{{ title }}</title>
</head>
<body>
<!-- Header -->
{% block header %}
<div class="container-fluid">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <ul class="nav col-md-6 mb-2 mb-md-0 d-flex justify-content-start">
            {% for m in menu %}
            <li><a href="{% url m.url_name %}" class="nav-link px-2 link-dark">{{ m.title }}</a></li>
            {% endfor %}
        </ul>
        <ul class="nav col-md-6 mb-2 mb-md-0 d-flex justify-content-end">
            <li style="margin-right:15px;margin-top:5px;">
                <a href="{% url 'cart:cart_detail' %}"><img
                        src="{% static 'ShopApp/image/cart.svg'%}" style="width:30px;"></a>
            </li>
            {% if request.user.is_authenticated %}
            <li>
                <a href="{% url 'account:account_detail' %}" class="px-2">
                    <button type="button" class="btn btn-light">{{ user.username }}</button>
                </a>
            </li>
            <li>
                <a href="{% url 'shop:logout' %}">
                    <button type="button" class="btn btn-dark">Выйти</button>
                </a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'shop:login' %}" class="px-2">
                    <button type="button" class="btn btn-light">Войти</button>
                </a>
            </li>
            <li>
                <a href="{% url 'shop:register' %}">
                    <button type="button" class="btn btn-dark">Регистрация</button>
                </a>
            </li>
            {% endif %}
        </ul>
    </header>
</div>
{% endblock header %}
<!-- End Header -->
<!-- Main -->
<div class="container-fluid">
    <div class="row">
        {% block categories %}
        <div class="col-lg-2 col-md-12 col-sm-12 py-3 ">
            <div class="d-flex justify-content-center col-md-12">
                    <ul class="list-group w-100" style="width:13rem;">
                        {% if cat_selected == 0 %}
                        <li class="list-group-item text-center">Все категории</li>
                        {% else %}
                        <li class="list-group-item text-center"><a href="{% url 'shop:home' %}" class="list"
                                                                   style="text-decoration:none; color:#111111;">Все
                            категории</a>
                        </li>
                        {% endif %}
                        {% for c in cats %}
                        {% if c.products__count > 0%}
                        {% if c.pk == cat_selected %}
                        <li class="list-group-item text-center">{{ c.name }}</li>
                        {% else %}
                        <li class="list-group-item text-center"><a href="{{ c.get_absolute_url }}" class="list"
                                                                   style="text-decoration:none; color:#111111;">{{ c.name }}</a>
                        </li>
                        {% endif %}
                        {% endif %}
                        {% endfor %}
                    </ul>
            </div>
        </div>
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
</div>
<!-- End Main -->
<!-- Footer -->
<div class="container-fluid" bis_skin_checked="1">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center" bis_skin_checked="1">
            <span class="text-muted">© 2022 bondarenkodv</span>
        </div>
    </footer>
</div>
<!-- End Footer -->
</body>
</html>

ShopApp/templates/ShopApp/base_login_register.html
{% load static %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'ShopApp/css/style.css'%}">

<body class="text-center">
<div class="d-flex justify-content-center">
    {% block auth %}
    {% endblock %}
</div>
</body>
</html>

ShopApp/templates/ShopApp/index.html
{% extends 'ShopApp/base.html' %}
{% block content %}
{% load static %}
<div class="col-lg-10 col-md-12 card-group">
    {% for u in unit %}
    {% if u.image %}
    <div class="col-lg-4 col-md-6 col-sm-6 col-12 py-3 d-flex justify-content-center">
        <div class="card" style="width:19rem; ">
            <img src="{{ u.image.url }}" class="card-img-top" style="height:250px">
            <div class="card-body">
                <h5 class="card-title text-center">{{ u.name }}</h5>
                <p class="card-text text-center" style="font-weight:bold;">{{ u.price }} &#8381;</p>
                <ul class="nav d-flex justify-content-center">
                    <li style="margin-right:10px;">
                        <a href="{{ u.get_absolute_url }}" class="btn btn-dark">Подробнее</a>
                    </li>
                    <li style="margin-right:10px;">
                        <form action="{% url 'cart:cart_add' u.id %}" method="post">
                            <p style="display: none; height:0px; width:0px;">{{ cart_product_form }}</p>
                            {% csrf_token %}
                            <button type="submit" style="border: none; outline: none; background: transparent;"><img
                                    src="{% static 'ShopApp/image/cart.svg'%}" style="width:30px; height:40px;"></button>
                        </form>
                    </li>
                    <li>
                        <form action="{% url 'favourites:add_to_favourites' u.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" style="border: none; outline: none; background: transparent;"><img
                                    src="{% static 'ShopApp/image/favourites.svg'%}" style="width:40px; height:40px;"></button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    {% endif %}
    {% endfor %}
</div>
{% endblock %}

ShopApp/templates/ShopApp/login.html
{% extends 'ShopApp/base_login_register.html' %}
{% load static %}
{% block auth %}
<ul style="margin-top:15%;">
    <li class="list-group-item">
        <h1 class="h3">Авторизация</h1>
    </li>
    <li class="list-group-item my-4">
        <form method="post">
            {% if form.errors %}
            <div class="alert alert-danger text-center my-1" role="alert">Неправильный логин или пароль</div>
            {% endif %}
            {% csrf_token %}
            {% for f in form %}
            <div class="fieldWrapper">
                <label for="{{ form.id_for_label }}">{{ f.label }}</label>
                {{ f }}
                {% if f.errors %}
                <div class="alert alert-danger text-center my-1" role="alert"><p class="text-center">{{ f.errors }}</p>
                </div>
                {% else %}
                <div></div>
                {% endif %}
            </div>
            {% endfor %}
            <button type="submit" class="w-100 my-3 btn btn-lg btn-primary">Войти</button>
        </form>
    </li>
    <p class="mt-5"><a href="{% url 'shop:register'%}" class="text-scope">Нет аккаунта? Зарегистрируйтесь</a></p>
    <p class="mt-1"><a href="{% url 'shop:home' %}" class="text-scope">На главную</a></p>
    <p class="mt-5 mb-3 text-muted">© bondarenkodv</p>
</ul>
{% endblock %}

ShopApp/templates/ShopApp/register.html
{% extends 'ShopApp/base_login_register.html' %}
{% load static %}
{% block auth %}
<ul style="margin-top:5%;">
    <li class="list-group-item">
<h1 class="h3 mb-4 fw-normal">Регистрация</h1>
    </li>
<li class="list-group-item">
<form method="post" style="width:300px; " class="text-center">
    {% csrf_token %}
    {% for f in form %}
    <div class="fieldWrapper">
        <label for="{{ form.from_email.id_for_label }}">{{ f.label }}</label>
        {{ f }}
        {% if f.errors %}
        <div class="alert alert-danger text-center my-1" role="alert"><p class="text-center">{{ f.errors }}</p>
        </div>
        {% else %}
        <div></div>
        {% endif %}
    </div>
    {% endfor %}
    <button type="submit" class="w-100 my-3 btn btn-lg btn-primary">Зарегистрироваться</button>
</form>
</li>
<p class="mt-3 text-scope"><a href="{% url 'shop:login'%}" class="text-scope">Уже зарегистрированы? Войти</a></p>
<p class="mt-1"><a href="{% url 'shop:home' %}" class="text-scope">На главную</a></p>
<p class="mt-5 mb-3 text-muted">© bondarenkodv</p>
</ul>
{% endblock %}

ShopApp/templates/ShopApp/show_product.html
{% extends 'ShopApp/base.html' %}
{% load static %}
{% block content %}
<div class="col-lg-10 col-md-12">
    <div class="col-lg-5 col-md-12 py-3 d-flex justify-content-center">
        <img src="{{ product.image.url }}" alt="" style="width:300px; height:300px;">
    </div>
    <div class="col-lg-5 col-md-12 py-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><h3>{{ product.name }}</h3></li>
            <li class="list-group-item">Наличие:{% if product.available %} Есть в наличии{% else %} Нет в наличии{% endif %}
            </li>
            <li class="list-group-item"><p>Цена: {{ product.price }}&#8381;</p></li>
            <li class="list-group-item">
                <ul class="nav d-flex justify-content-start">
                    <li>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    <p style="display: none; height:0px; width:0px;">{{ cart_product_form }}</p>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark">
                        Добавить в корзину
                    </button>
                </form>
                        </li>
                    <li>
                <form action="{% url 'favourites:add_to_favourites' product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" style="border: none; outline: none; background: transparent;">
                        <button type="submit" style="border: none; outline: none; background: transparent;"><img
                                src="{% static 'ShopApp/image/favourites.svg'%}" style="width:40px;"></button>
                    </button>
                </form>
                    </li>
                    </ul>
            </li>
            <li>

            </li>
        </ul>
    </div>
    <div class="col-lg-10 col-md-12 py-3">
        <h4 class="product_description">Описание товара</h4>
        <p style="font-size:14px;">{{ product.description }}</p>
    </div>
</div>

{% endblock %}